### ISSUE TITLE
[bug] Transparent element of notification widget covers part of the page on < 1024px

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-notifications#130]
The widget covers a part of the page which if hovered with the mouse becomes clickable, but happens only when the window size is narrower than 1024px.

![Screenshot from 2020-09-18 15-52-33](https://user-images.githubusercontent.com/841044/93644366-741bab80-f9c7-11ea-8430-c3a884bf0c0d.png)

**Comment by niteshsinha17** [comment]
I would like to work on it.
