### ISSUE TITLE
[ux] Add escape key handler for object notification widget

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-notifications#133]
The object notification widget does not get closed when escape key is pressed from the keyboard. The widget should get closed and focus should return to "UNSUBSCRIBE"  button. In my opinion this is hurting accessibility of the webpage.

This functionality has been already implemented for the notification widget, which could be used for reference. 
https://github.com/openwisp/openwisp-notifications/blob/c110d41293aba96e6f0cf9a6d21968ceb39b8f1b/openwisp_notifications/static/openwisp-notifications/js/notifications.js#L43-L51

**Comment by niteshsinha17** [comment]
I would like to work on this. Please assign it to me.

**Comment by pandafy** [comment]
@niteshsinha17 please go ahead!
