### ISSUE TITLE
[change] Change wording of "unsubscribe" button

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-notifications#136]
I think we could rename this to "Silence notifications", what do you think @pandafy?

**Comment by pandafy** [comment]
I would prefer something concise, because having something as verbose as "Silence Notifications" may not look great on small screens.

**Comment by nemesisdesign** [comment]
@pandafy I see. it's better to wait to have more feedback from users before deciding with this. I will keep this open as a reminder for the future but it's not a priority right now.

**Comment by Purhan** [comment]
How about "Mute"? Short and simple :)

**Comment by pandafy** [comment]
Let's also use this opportunity to update the tooltip of the button to "Disable notifications for this object".

**Comment by nemesisdesign** [comment]
Ok, so let's change it to "Silence notifications" and let's change the tooltip to "Disable notifications for this object" when notifications are enabled and "Enable notifications for this object" when notifications are disabled.
