### ISSUE TITLE
[release] Release 0.2.1 version

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-notifications#138]
@pandafy, when you have time, could you release a 0.2 version please? So we can close https://github.com/openwisp/openwisp-controller/issues/282.

**Comment by pandafy** [comment]
@nemesisdesign did you mean 0.2.1? 0.2 has been already released. [These are the changes](https://github.com/openwisp/openwisp-notifications/compare/d387f6ade9adaddb09d67b0998461302bb259d19...master) added to master since then.
