### ISSUE TITLE
Notification being sent to all users

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-notifications#15]
If no organization and no recipient is provided in `notify.send()`then notifications will be sent to all users who have opted-in to receive notifications (`notificationuser__receive=True`). 

https://github.com/openwisp/openwisp-notifications/blob/d2b2dd86b2e0657c383fed23c00e124a4ee2d1a0/openwisp_notifications/handlers.py#L32-L51

The problem arises at this statement
```
where = where | (Q(is_superuser=True) & Q(notificationuser__receive=True))
```
which update where as
```
(OR: ('notificationuser__receive', True), (AND: ('is_superuser', True), ('notificationuser__receive', True)))
```
A straight forward solution will be something like this
```
    where = Q()
    if target_org:
        where = Q(is_staff=True) & Q(openwisp_users_organization=target_org) & Q(notificationuser__receive=True)

    if recipient:
        # Check if recipient is User, Group or QuerySet
        if isinstance(recipient, Group):
            recipients = recipient.user_set.filter(notificationuser__receive=True)
        elif isinstance(recipient, (QuerySet, list)):
            recipients = recipient
        else:
            recipients = [recipient]
    else:
        where = where | (Q(is_superuser=True) & Q(notificationuser__receive=True))
        recipients = (
            User.objects.select_related('notificationuser')
            .order_by('date_joined')
            .filter(where)
        )
```
While this works, I have doubts that follows best practices since `notificationuser__receive=True` is redundant in this case. I would like to know your thoughts before  proceeding. 

This bug got introduced in #7

**Comment by NoumbissiValere** [comment]
Yes making `notificationuser__receive=True` is not good practice. One thing you could do is something like this

```
where = Q()
    if target_org:
        where = Q(is_staff=True) & Q(openwisp_users_organization=target_org)

    if recipient:
        # Check if recipient is User, Group or QuerySet
        if isinstance(recipient, Group):
            recipients = recipient.user_set.filter(notificationuser__receive=True)
        elif isinstance(recipient, (QuerySet, list)):
            recipients = recipient
        else:
            recipients = [recipient]
    else:
        where = where | Q(is_superuser=True)
        recipients = (
            User.objects.select_related('notificationuser')
            .order_by('date_joined')
            .filter(where)
        )
    where = where & Q(notificationuser__receive=True)
```

**Comment by NoumbissiValere** [comment]
That's checking the `Q(notificationuser__receive=True)` when you are about to get the last `where` before you send the notification. 

I don't know if that answers your worry :sweat_smile:

**Comment by pandafy** [comment]
Thanks @NoumbissiValere , I have done something like that here.
https://github.com/openwisp/openwisp-notifications/blob/0eef0961159e929dd3673b215451e4e838191663/openwisp_notifications/handlers.py#L32-L50
I will add more test cases before opening a pull request.
