### ISSUE TITLE
[bug] Fix project dependent test cases

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-notifications#157]
The following test checks whether a notification preference has been made for the default notification type. In other modules of openwisp(openwisp-controller) we unregister this notification type. As a consequence, this test fails when the test suite is run outside of the test project of openwisp-notifications. 

https://github.com/openwisp/openwisp-notifications/blob/19bf2ed59b11507d6b025e67fbd6973d4f83673f/openwisp_notifications/tests/test_admin.py#L200-L206

One solution to this could be to check for the default organization instead of checking for default notification type.

**Comment by b-thebest** [comment]
Can I work on this

**Comment by pandafy** [comment]
@b-thebest you can work on this. But, don't spam on every other issue opened in OpenWISP. Join [OpenWISP's Gitter channel](https://gitter.im/openwisp/general) if you need help.

**Comment by b-thebest** [comment]
@pandafy I found many issues that I can solve that's why multiple comments. Please assign this task to me, I will do it asap

**Comment by pandafy** [comment]
It is a good idea to take a single issue at a time. You won't get overwhelmed with work all at once.

**Comment by 2001asjad** [comment]
Hello @pandafy , there are many tests that are showing errors and some are failing as well. Could you please tell me more about solving them ?
Thanks

**Comment by pandafy** [comment]
@2001asjad can you share which tests are showing errors or failing for you?

**Comment by 2001asjad** [comment]
Hello @pandafy  I ran `./runtests.py -v 2` for a detailed analysis for the tests. Here are some of the screenshots of the tests that had errors.
![SS1](https://user-images.githubusercontent.com/60435499/105138255-a296c800-5b1a-11eb-8047-fc38a69efe41.png)
![SS2](https://user-images.githubusercontent.com/60435499/105138294-b04c4d80-5b1a-11eb-98ea-fb75efc00c37.png)
![SS3](https://user-images.githubusercontent.com/60435499/105138318-b6dac500-5b1a-11eb-9e6a-e20506840732.png)

Hope to discuss more about it.

**Comment by pandafy** [comment]
@2001asjad make sure the redis server is up. If you are using docker-compose, then `dcoker-compose up -d redis` should do the trick.

**Comment by 2001asjad** [comment]
Yes @pandafy I didn't run the redis server earlier , now there aren't any errors.

**Comment by SidharajYadav** [comment]
Hello, how i can contribute on this issuse

**Comment by pandafy** [comment]
@SidharajYadav read issue description and ask if something is not clear.
