### ISSUE TITLE
[fix] Receives notification even when disabled during development 

### ISSUE THREAD

**Issue by niteshsinha17** [openwisp/openwisp-notifications#159]
**Current Behavior**
Disable notifications during development and then run `manage.py create_notification` command. You will get a notification even when you have disabled it.

**Expected Behavior**
You should not receive any notification. 

**Root Cause**
https://github.com/openwisp/openwisp-notifications/blob/19bf2ed59b11507d6b025e67fbd6973d4f83673f/openwisp_notifications/management/commands/__init__.py#L12-L15
`default_org` is passed as target here and it does not have `organization_id` in below code so this is causing the bug. 
https://github.com/openwisp/openwisp-notifications/blob/19bf2ed59b11507d6b025e67fbd6973d4f83673f/openwisp_notifications/handlers.py#L64

By changing `organization_id` to `id` it is solving the bug. But this is not a proper solution so we need to find a better solution for it.

**Comment by prsndp** [comment]
I want to work on this issue, can you assign me this task ??

**Comment by niteshsinha17** [comment]
@ppabcd You can start working on it. Go ahead!

**Comment by prsndp** [comment]
@niteshsinha17  me?

**Comment by niteshsinha17** [comment]
> @niteshsinha17 me?

Yes, You can start

**Comment by prsndp** [comment]
@niteshsinha17  Thanks 👍🏻

**Comment by prsndp** [comment]
Thanks  @devkapilbansal

**Comment by pandafy** [comment]
> `default_org` is passed as target here and it does not have `organization_id` in below code so this is causing the bug.
> https://github.com/openwisp/openwisp-notifications/blob/19bf2ed59b11507d6b025e67fbd6973d4f83673f/openwisp_notifications/handlers.py#L64
> 
> By changing `organization_id` to `id` it is solving the bug. But this is not a proper solution so we need to find a better solution for it.

The above change should not be made for the sake for fixing `create_notification` command because it will break integration for everything else. 

Instead, I will suggest to update [BaseCreateNotificationCommand](https://github.com/openwisp/openwisp-notifications/blob/19bf2ed59b11507d6b025e67fbd6973d4f83673f/openwisp_notifications/management/commands/__init__.py#L12-L15) as follows

```
 class BaseCreateNotificationCommand(BaseCommand): 
     def handle(self, *args, **kwargs): 
         default_org = Organization.objects.first()
         default_org.organization_id = default_org.id
         notify.send(sender=default_org, type='default', target=default_org) 
```

Yes this is a hack, but the command is only used in the development environment so it should not affect anything. I have not tested above code myself, additional debugging might be required.

**Comment by yashikajotwani12** [comment]
I would like to work on this issue.

**Comment by pandafy** [comment]
Hey @yashikajotwani12! Please finish the work on https://github.com/openwisp/django-swappable-models/pull/33 before going ahead on this. One step at a time. :)
Thanks!

**Comment by yashikajotwani12** [comment]
> Hey @yashikajotwani12! Please finish the work on [openwisp/django-swappable-models#33](https://github.com/openwisp/django-swappable-models/pull/33) before going ahead on this. One step at a time. :) Thanks!

Okay, I would. Thank you
