### ISSUE TITLE
[feature] Introduce mechanism to clear the cache on specific signals

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-notifications#164]
When items are renamed, old name still shows up.

We should introduce a generic mechanism to listen for change signals of objects that are used in notifications, so that the cache can be re-generated for all elements related to that specific object.

Question: it is possible to clear the cache only for specific objects or would we need to clear the entire cache?

We could allow other modules to register their own model and signals to listen to, eg:

```
from openwisp_controller.config.signals import device_name_changed 

register_notification_observation((Device, device_name_changed))
```

This could go in ow-controller and would trigger a refresh of the cache when the device name is changed.

I think this is similar to https://github.com/openwisp/openwisp-notifications/issues/163, maybe we can introduce a solution which can handle both cases, we need a solution to allow other modules to tell ow-notifications when to refresh the cache in an efficient way.

PS: the `device_name_changed` signal does not exist yet, but we can add it once the ideas in this issue are confirmed, see https://github.com/openwisp/openwisp-controller/issues/361.

**Comment by pandafy** [comment]
> Question: it is possible to clear the cache only for specific objects or would we need to clear the entire cache?

Yes, it is possible to clear cache of a particular object. 

To obtain cache key of an object, `obj`:

```python
from django.contrib.contenttypes.models import ContentType
from openwisp_notifications.models import Notification

content_type = ContentType.objects.get_for_model(id._meta.model)
cache_key = Notification._get_cache(content_type.id, object.id)
```

Now, you can clear the cache with. 

```python
from django.core.cache import cache

cache.delete(cache_key)
```

Cache will be automatically populated on the next fetch operation, so we don't need to update the value of cache. Or we can update the cache, it is completely upto the implementation.
