### ISSUE TITLE
[refactor] notification_widget(): make strings translatable and move HTML code to template

### ISSUE THREAD

**Issue by nemesifier** [openwisp/openwisp-notifications#203]
This code has 2 problems:

https://github.com/openwisp/openwisp-notifications/blob/0cc9aca6593979585f717a5fa375f749dfd4386a/openwisp_notifications/templatetags/notification_tags.py#L37-L61

1. I believe it would be better to move the HTML code to a template and load it with the template loader functions offered by Django.
2. User facing strings shall be flagged as translatable.

**Comment by nemesisdesign** [comment]
> I think we can directly add this code to [openwisp_notifications/templates/admin/base_site.html](https://github.com/openwisp/openwisp-notifications/blob/master/openwisp_notifications/templates/admin/base_site.html). It is not really reusable.
> 
> Same goes for `notification_toast()`
> 
> https://github.com/openwisp/openwisp-notifications/blob/40e57ad3ddaaba011f4e505b61706766164d346c/openwisp_notifications/templatetags/notification_tags.py#L58-L59

:+1:
