### ISSUE TITLE
[bug] Notification toast does not close on slow internet connections

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-notifications#211]
The frontend performs two operation upon receiving a notification on websocket:
1. It displays the notification 
2. It reloads the notification widget

On a slow network, it can take time to reload the widget while the notification toast is already being displayed (notification content is sent via WS). 

Clicking on the close icon of notification toast not only closes the notification toast but also flags the notification as read(by removing the `unread` class of the notification element in notification widget and updating the backend via WS). Performing above observation in a state where notification widget is still reloading yields this on console:

![Screenshot from 2021-12-03 22-20-20](https://user-images.githubusercontent.com/32094433/144640941-345ca411-df8e-44d0-adec-b9709bad0fdf.png)

As a result, the notification toast does not get closed. 

Following code is responsible for flagging notification as read. 

https://github.com/openwisp/openwisp-notifications/blob/67f344b04132676f16e4485388a68966ab8192c0/openwisp_notifications/static/openwisp-notifications/js/notifications.js#L324-L338

**Possible Fix**
Remove the `throw error` statement form the catch clause.

**Comment by nemesisdesign** [comment]
That is, make the UI change instantaneous and let the server sync happen in the background?
