### ISSUE TITLE
[change] Add celery time limits to tasks

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-notifications#217]
Depends on https://github.com/openwisp/openwisp-utils/issues/271.

Let's ensure all tasks have time limits defined. For similar tasks we may share the same settings.

**Comment by dishantsethi** [comment]
I'll be working on this.
@nemesisdesign What should be the time_limit for celery tasks?
By default, tasks don’t time out. So, should I set some large global default timeout for tasks and override in specific tasks? 

For example:

In settings.py
```
CELERYD_TASK_SOFT_TIME_LIMIT = 60
```

In tasks.py
```
@shared_task(soft_time_limit=5)
def func():
```

**Comment by nemesisdesign** [comment]
@dishantsethi this issue depends on https://github.com/openwisp/openwisp-utils/issues/271, on which @pandafy is working on.
