### ISSUE TITLE
[feature] Add dedicated notification type for internal errors

### ISSUE THREAD

**Issue by nemesifier** [openwisp/openwisp-notifications#254]
Some times errors may happen in the background, at the moment we do not have a way to show these errors to users.

We could define a notification type for these situations and implement something slightly different in the UI: when clicking on such a notification, instead of being redirected to the target_url, an overlay can be opened with the long description of the error.

The overlay then can show a button which will direct the user to the target object.

**Comment by BassCoder2808** [comment]
Hi @nemesisdesign, I wanted to contribute to this issue, I have installed the openwisp-notifications and the setup part is done for the same, I wanted to get a more brief understanding of this, like what exactly is the indented behavior and the steps to reproduce the issue in the background based on which we can notify the user

**Comment by sawaisinghh** [comment]
Hey @nemesisdesign, I might be able to fix this issue. can you please assign it to me?

**Comment by pandafy** [comment]
Email notifications should be disabled for this notification type.
