### ISSUE TITLE
[bug] Strange interaction with firmware-upgrader

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-notifications#26]
I have launched a firmware upgrade operation on an instance where I upgraded to the latest dev versions of openwisp-monitoring and openwisp-notifications and I started noticing notifications which we have not introduced yet, eg:

Giving up, device not reachable anymore after upgrade

![Screenshot from 2020-05-25 14-14-08](https://user-images.githubusercontent.com/841044/82838597-506dac00-9e92-11ea-8975-3f527c381890.png)

timed out

![Screenshot from 2020-05-25 14-16-38](https://user-images.githubusercontent.com/841044/82838625-60858b80-9e92-11ea-8103-5497585eeca7.png)

I wonder WTF is happening?

Provided that this is a feature we do want to introduce, but as far as I know by the last time I reviewed the code, we were not doing this explicitly, so I think something wrong is going on here and it should be fixed.

@pandafy do you have any idea?

@NoumbissiValere @Vivekrajput20 FYI :point_up:

**Comment by pandafy** [comment]
This is new to me as well.  It must be getting generated in monitoring module. I will look into it later today.

**Comment by pandafy** [comment]
I found out the source for this notification. 

https://github.com/openwisp/openwisp-monitoring/blob/911e01c6ac6bc632f4491685f087eff31b84462c/openwisp_monitoring/device/apps.py#L104-L135

I thought there are only two types of notifications in openwisp-monitoring, `threshold crossed` and returned under `threshold` which are created in monitoring part of openwisp-monitoring. Apologies for my negligence. I shall create notification types for all such possible cases.

**Comment by nemesisdesign** [comment]
Thanks @pandafy to help me debug this.
