### ISSUE TITLE
[docs] Incorrect syntax

### ISSUE THREAD

**Issue by nepython** [openwisp/openwisp-notifications#32]
I was referring to #19 for [openwisp-monitoring/#86](https://github.com/openwisp/openwisp-monitoring/issues/86). Nice work in this PR :clap:

I noticed a minor typo [here](https://github.com/openwisp/openwisp-notifications/blame/master/README.rst#L299) so opened this issue :smile:

...models.Site`  **--->** ...models.Site``

>**CC**: @pandafy

**Comment by pandafy** [comment]
Thanks @nepython , highly appreciated :clap:  . I have addressed this in #31 
Here :smile: : 
https://github.com/openwisp/openwisp-notifications/pull/31/files#diff-88b99bb28683bd5b7e3a204826ead112R299
