### ISSUE TITLE
[chores] Remove support for "url" parameter in notify signal

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-notifications#36]
In our use case with openwisp-monitoring, the `url` parameter is only passed for `device`. Since we are already building `target_url` for target object in openwisp-notifications, therefore `url` parameter can be removed to keep things simple.

**Comment by nemesisdesign** [comment]
@pandafy the possibility of passing an arbitrary URL can be useful. Can you link the part of the code which implements this? If it's not many lines, we can keep it, we just have to make sure in a comment and in the README that it's an optional feature.

**Comment by pandafy** [comment]
Apologies for late reply, I might have missed opening email for this one. :sweat_smile: 

These lines of code can be simplified after removing that functionality:
https://github.com/openwisp/openwisp-notifications/blob/28fa8b0536719499d5e555d5ea2a7e399c30706b/openwisp_notifications/models.py#L136-L143

https://github.com/openwisp/openwisp-notifications/blob/28fa8b0536719499d5e555d5ea2a7e399c30706b/openwisp_notifications/templates/openwisp_notifications/email_template.html#L80-L88
