### ISSUE TITLE
[feature] Allow users to ignore notifications on a specific object

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-notifications#38]
- [ ] Allow a user to ignore notifications for a specific object, permanently or temporarily (1 day, 3 days, 1 week, 1 month, custom duration)
- [ ] Use celery to enable disabled notifications after passage of the specified time
- [ ] Provide an API to activate this feature of an object (eg: `PUT /api/v1/notification/ignore/<content-type>/<object-id>/`)
- [ ] Provide an API to deactivate this feature for an object (eg: `DELETE /api/v1/notification/ignore/<content-type>/<object-id>/`)

**Project Idea**
>Allow users to disable notifications for specific objects, either permanently or until a specific date, with predefined set of durations: permanently, 1 day, 3 days, 1 week, 1 month, custom date. In the case the disabling is temporary, the setting should be deleted automatically after expiration by a simple celery task which is run periodically with celery beat.

**Comment by nemesisdesign** [comment]
I think we can add a dedicated model for this, which would have a generic relation and would also specify something like a date range or period, so before sending notifications we can check if an ignore setting exists, including information about date time in the query (ensure indexes are correctly configured to make sure the query will be fast).

Did you have anything different in mind?
