### ISSUE TITLE
[enhancement] Make defining base_site.html optional

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-notifications#42]
Presently for a derivative app, we need to define `admin/base_site.html` so that it can work properly. 
The main reason for this is presence of app label `openwisp_notifications` in `url` tag. 

A way to solve this will be to override `ModelAdmin` and pass app label as a variable.

**Comment by nemesisdesign** [comment]
@pandafy is this still relevant?

**Comment by pandafy** [comment]
This issue became obsolete after https://github.com/openwisp/openwisp-notifications/pull/204
