### ISSUE TITLE
[feature] Notification settings: allow users to disable notifications by type, organization, medium

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-notifications#5]
**Goals**
- [x] Allow user to disable notifications by notification type. 
- [x] Allow possibility to disable only email notifications or web notifications.
- [x] Allow disabling notification for an organization.

**Project Idea**
> Allow users to disable notifications by notification types, right now it's only possible to enable or disable the notifications globally.
For each notification type and organization the user should be able to disable either all notifications or only the email notification.
Example: Receive notifications for organization "default"?
Two checkboxes: Web and Email; if email is checked also web is checked automatically (because the notification depends on the basic notification being created).
Such a solution would give us the possibility to implement mobile push notifications in the future by adding a new checkbox for mobile notifications.

> Allow users to disable notifications for specific objects, either permanently or until a specific date, with predefined set of durations: permanently, 1 day, 3 days, 1 week, 1 month, custom date. In the case the disabling is temporary, the setting should be deleted automatically after expiration by a simple celery task which is run periodically with celery beat.

**Comment by nemesisdesign** [comment]
Regarding the options concerning the user, we need to have a page where the user can control their own notifications, so we can link to it from the notification text (eg: `if you want to stop receiving this notifications you can do so from your notification settings`).

**Comment by nemesisdesign** [comment]
@pandafy I think we can split this issue.

The first goal should be the following:

- Allow a user to disable notifications by notification type, organization (if user is member only of one org, hide this field) and medium (web or email)

I think it should be something like this, we should have a DB table dedicated to these settings and each row should have:

- `user`: foreign key to user
- `type` choice string field indicating the available notification types
- `organization` (if user is only member of one org, set that org automatically and hide the field)
- `email` a boolean defaulting to `True` indicating whether email notifications are enabled for this type and organization
- `web` a boolean defaulting to `True` indicating whether web notifications are enabled for this type and organization

unique together: user, type, organization.

Rows should be created automatically at startup or with migrations (maybe doing it at startup automatically will save us from the pain of having to write a migration every time we add a new notification type).

We should add an API to allow editing these objects for the current logged in user, something like:

`/api/v1/account/notification-settings/` or `/api/v1/notification/settings/`

Then we can add this as an inline admin in `UserAdmin`, disable adding and deleting rows, allow only changing the existing objects.

Then, when retrieving the recipients of notifications, you should join (`select_related`) the user table with this new table and filter accordingly.

The rest of the points we can explore in https://github.com/openwisp/openwisp-notifications/issues/38, and we can focus that effort on special cases, eg: a user wanting to disable the notification permanently or temporary on a specific object (right now object will be always device but in the future we may have notifications related to other objects).

**Comment by nemesisdesign** [comment]
PS: rows should also listen to changes to `OrganizationUser` objects (which represent the organization membership of a user).
When an OrganizationUser object is added, notification settings for all types, OrganizationUser.user and OrganizationUser.organization should be created.
When an OrganizationUser object is removed notification settings for all types, OrganizationUser.user and OrganizationUser.organization should be removed. 

If this kind of operation is additionally performed also at startup, we can ensure that if a notification type is added, the related settings will be created for users. An alternative of doing it at startup would be to listen to signals related to django migrations, which are performed during upgrades, this may be better since we wouldn't slow down the startup of the application.
