### ISSUE TITLE
[enhancement] Use IndxedDB for optimizing notification widget

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-notifications#58]
**Current implementation:**

When a user opens any admin webpage. an API call to server is made through AJAX and notifications are fetched. 
When user scrolls through the notification widget, more notifications are fetched from the server. 
The notifications are stored on runtime memory of the browser to prevent subsequent calls to server.
Notification is marked read by sending a message through web sockets.

**Shortcomings**
- We need to keep track of read and unread notifications in the memory
- If a notification is created/deleted the notification widget is refreshed(reloaded) from the  server.
- If user visits different pages on the admin site, API call are made to fetch same data each time.

**Proposed Solution**
- Use IndexedDB to cache notification data locally.
- When a user visits admin webpage for first time, API call is made to the server. Those notifications instead of getting stored in memory will be stored in IndexedDB. 
- When user receives a new notification(through websocket) it will be updated in the IndexedDB and the notification will be updated. 
- This will persist data over different webpages visited on admin site by user

**Comment by nemesisdesign** [comment]
Nice :+1:!

**Comment by nemesisdesign** [comment]
Maybe we don't need this. I think performance is doing ok right now.

**Comment by pandafy** [comment]
This feature sounds great on paper. I remember while implementing it in https://github.com/openwisp/openwisp-notifications/pull/57, I felt that it was making the code complicated. So, I decided to open up a new issue to plan before implementing it.

In opinion this is not immediately required but will be good to have in future. Currently we don't provide any means for deleting notifications by a user which sounds unconventional. This will be very much required for adding that functionality.

I will suggest to keep this open until we really need it.
