### ISSUE TITLE
[chores] Fix hardcoded URLs in test_api

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-notifications#75]
@pandafy always use `reverse` when generating URLs, I see there are some occurrences of hardcoded urls in `test_api.py`, if there are other occurrences fix those as well please.

**Comment by pandafy** [comment]
@nemesisdesign are you referencing to this
https://github.com/openwisp/openwisp-notifications/blob/00ba08519e7bad41f9c0a8a20845ddd36ff2fa2a/openwisp_notifications/tests/test_api.py#L57-L60

or this?
https://github.com/openwisp/openwisp-notifications/blob/00ba08519e7bad41f9c0a8a20845ddd36ff2fa2a/openwisp_notifications/tests/test_api.py#L53

**Comment by nemesisdesign** [comment]
> @nemesisdesign are you referencing to this
> https://github.com/openwisp/openwisp-notifications/blob/00ba08519e7bad41f9c0a8a20845ddd36ff2fa2a/openwisp_notifications/tests/test_api.py#L57-L60
> 
> or this?
> https://github.com/openwisp/openwisp-notifications/blob/00ba08519e7bad41f9c0a8a20845ddd36ff2fa2a/openwisp_notifications/tests/test_api.py#L53

I'm referring to all occurrences of `http://testserver/...`, the former looks like one of those.
