### ISSUE TITLE
[enhancement] Add `type_name` key to notification type 

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-notifications#88]
Currently, [register_notification_type](https://github.com/openwisp/openwisp-notifications/blob/88eb6a4817a8f9e086a86edd23aa9204e90440dd/openwisp_notifications/types.py#L41) functions requires `type_name` to be provided separately. 

Add `type_name` key in notification type configuration and use it instead of requiring an argument while registering notification type.

**Comment by nemesisdesign** [comment]
Don't worry, we'll handle this internally in openwisp-monitoring, this is not required here.
