### ISSUE TITLE
[js widget] UX problems found during testing

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-notifications#91]
### Where are all the notifications?

the widget shows always 10 notifications, even if there are more, it doesn't seem to load new data

### Flagging notifications as read

The current way we implemented reading notifications is showing its limits: notifications are marked as read as soon as the widget is opened, which doesn't give us a chance to distinguish between read and unread ones.

A possible step forward could be to flag them as read on hover. The alternative could be leave it as it was before, so that they're marked unread only if clicked, and is up to the user to click on "mark all as read" if they don't want to click over every one.

### HTTPs in dev

Clicking on a notification sends me to HTTPS also in dev mode.

@pandafy what do you think?

**Comment by pandafy** [comment]
I tried to quickly reproduce the first problem, but couldn't. I will try to find different scenarios which can raise this bug. If you can find something in network or console tab of debugger tools, it will make fixing it quicker. Can you please check whether API calls are being generated when you scroll to the bottom of the widget?

For the second problem, we can just increase the  timeout time below(line 303) to 5 seconds or more. This solution requires least change, but if you think flagging notification read on hover would be great, then we can proceed with that too. 
https://github.com/openwisp/openwisp-notifications/blob/cbfc852cfd36854f9bd4c90c5c1f1d418161d589/openwisp_notifications/static/openwisp-notifications/js/notifications.js#L296-L311

**Comment by nemesisdesign** [comment]
> I tried to quickly reproduce the first problem, but couldn't. I will try to find different scenarios which can raise this bug. If you can find something in network or console tab of debugger tools, it will make fixing it quicker. Can you please check whether API calls are being generated when you scroll to the bottom of the widget?

Seems to be related to the screen height, if I resize the window to be smaller the srollbar is shown.
I think we can try loading 20 or even 30 notifications by default so the scrollbar will always appear.

> For the second problem, we can just increase the timeout time below(line 303) to 5 seconds or more. This solution requires least change, but if you think flagging notification read on hover would be great, then we can proceed with that too.

Yes I would try on hover and see how it goes, the current approach doesn't feel optimal while using it.

**Comment by pandafy** [comment]
> Seems to be related to the screen height, if I resize the window to be smaller the srollbar is shown.
> I think we can try loading 20 or even 30 notifications by default so the scrollbar will always appear.

This is the underlying problem: 
https://github.com/openwisp/openwisp-notifications/blob/cbfc852cfd36854f9bd4c90c5c1f1d418161d589/openwisp_notifications/static/openwisp-notifications/css/notifications.css#L101-L105

Setting even a higher number might fail, if a user uses screen in portrait. :sweat_smile: 
I will set definite height in pixels along with loading more notifications in the beginning.

**Comment by nemesisdesign** [comment]
> > For the second problem, we can just increase the timeout time below(line 303) to 5 seconds or more. This solution requires least change, but if you think flagging notification read on hover would be great, then we can proceed with that too.
> 
> Yes I would try on hover and see how it goes, the current approach doesn't feel optimal while using it.

PS: not on mouseover event but on mouseout event, that would be better since they will change color only after the mouse moves out.

> > Seems to be related to the screen height, if I resize the window to be smaller the srollbar is shown.
> > I think we can try loading 20 or even 30 notifications by default so the scrollbar will always appear.
> 
...
> Setting even a higher number might fail, if a user uses screen in portrait. 
> I will set definite height in pixels along with loading more notifications in the beginning.

ok :+1: 

Reporting here what we discussed on gitter: 

In this case I would calculate how many pixels are needed to show 10 notifications and set the max height to make sure at max 10 items are shown.
