### ISSUE TITLE
[models] Ensure models are loaded using swappable

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-notifications#95]
Look for all instances of `from openwisp_users.models import` and replace them with swappable model loading.
Eg: https://github.com/openwisp/openwisp-users/#2-inheriting-admin-classes

**Comment by pandafy** [comment]
It will be of best interest if we proceed with this after merging #69 . Since, I unknowingly made such changes there, doing same things here will only make us deal with conflicts.
